### ISSUE TITLE
Al intentar hacer checkout me pide campo "dni"

### ISSUE THREAD

**Issue by delfina-rossi** [ecloudsolutions/andreani#5]
Al hacer el proceso comun de checkout de magento, me salta este mensaje: '"DNI" es un valor necesario.' .....esto me impide continuar con el proceso de compra.

**Comment by meliloop** [comment]
consulte al soporte de integracion y me dijeron que el campo dni no es necesario... no se por que entonces lo pusieron como requerido.
si te sirve.. lo solucione haciendo un update en el atributo que se crea al instalar.
UPDATE eav_attribute SET is_required='0' WHERE attribute_code = 'dni';

**Comment by delfina-rossi** [comment]
genial gracias!
